name: Client Workflow

on:
  push:
    branches: [main]
    paths: [client/**]
  pull_request:
    branches: [main]
    paths: [client/**]

env:
  PROJECT_ID: mp-radar-365513
  APP_ENGINE_YML: './client/app.yml'

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build App
        run: |
          cd server
          npm ci
          cd ../client
          npm ci
          npm run build

      - id: auth
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Set `sha_short` Output
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - id: deploy
        name: Deploy To App Engine
        uses: 'google-github-actions/deploy-appengine@v0'
        with:
          deliverables: ${{ env.APP_ENGINE_YML }}
          project_id: ${{ env.PROJECT_ID }}

      - name: show output
        run: 'echo ${{ steps.deploy.outputs.url }}'
