name: Client Workflow

on:
  push:
    branches: [ main ]
    paths: [ client/** ]
  pull_request:
    branches: [ main ]
    paths: [ client/** ]

jobs:

  test:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3

      - name: Setup node js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run Tests
        run: |
          cd client
          npm ci
          npm run test:ci 

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3

      - name: Setup node js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Build App
        run: |
          cd client
          npm ci
          npm run build
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./client/dist/ s3://${{ secrets.S3_BUCKET_NAME }} --delete

      - name: Invalidate Cloudfront distribution
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"